#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin
#

export PATH=/data/local/tmp/tools:$PATH

stop mpdecision

echo 1 > /sys/class/kgsl/kgsl-3d0/force_clk_on
echo 1 > /sys/class/kgsl/kgsl-3d0/force_bus_on
echo 1 > /sys/class/kgsl/kgsl-3d0/force_rail_on
echo performance > /sys/class/kgsl/kgsl-3d0/devfreq/governor

export CK_CPU_FREQ_GOVERNER=performance
export CK_CPU_FREQ_FILE=cpuinfo_max_freq
export CK_CPU_ONLINE=1

. ck-set-cpu-online-and-frequency
