#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Anton Lokhmotov
#

echo "*** Available CPU frequencies:"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_available_frequencies

echo "*** Current CPU frequency from scaling:"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq

#echo "*** Current CPU frequency:"
#cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq

echo "*** Minimum CPU frequency:"
cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_min_freq

echo "*** Maximum CPU frequency:"
cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq

echo

echo "*** Available CPU governors:"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_available_governors

echo "*** Current CPU governor:"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
