#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Anton Lokhmotov
#

su -c cat /sys/class/misc/mali0/device/gpuinfo

echo

echo "*** Current GPU frequency (Hz):"
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/cur_freq

echo

echo "*** Minimum GPU frequency:"
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/min_freq

echo

echo "*** Maximum GPU frequency:"
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/max_freq

echo

echo "*** Current GPU governor:"
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/governor

echo

echo "*** Current GPU power policy:"
su -c cat /sys/class/misc/mali0/device/power_policy

echo

echo "*** Available GPU frequencies (Hz):"
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/available_frequencies

echo

echo "*** Available GPU governors:"
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/available_governors

