#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Anton Lokhmotov
#

echo "*** Current CPU frequency (kHz):"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq

#echo "*** Current CPU frequency:"
#cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq

# echo "*** Minimum CPU frequency:"
# cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_min_freq
 
# echo "*** Maximum CPU frequency:"
# cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq

echo

echo "*** Current CPU governor:"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

echo

echo "*** Available CPU frequencies (kHz):"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_available_frequencies

echo

echo "*** Available CPU governors:"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_available_governors

