#! /system/bin/sh
 
#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Anton Lokhmotov
#

# TODO: How to change the GPU governor? (the below approach doesn't work)
#if [ "$CK_GPU_FREQ_GOVERNOR" != "" ]; then
#  governor=$CK_GPU_FREQ_GOVERNOR
#else
#  governor=gpu_scene_aware
#fi
#echo "    Setting GPU governor policy to $governor ..."
#echo $governor | su -c tee /sys/class/misc/mali0/device/devfreq/gpufreq/governor

#echo

echo "    Printing current GPU frequency ..."
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/cur_freq
echo "    Printing minimum GPU frequency ..."
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/min_freq
echo "    Printing maximum GPU frequency ..."
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/max_freq
echo "    Printing all available GPU frequencies ..."
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/available_frequencies

echo

if [ "$CK_GPU_FREQ_INDEX" != "" ]; then
  index=$CK_GPU_FREQ_INDEX
else
  index=0
fi

if [ "$CK_GPU_FREQ_INDEX_MIN" != "" ]; then
  index_min=$CK_GPU_FREQ_INDEX_MIN
else
  index_min=$index
fi
echo "    Setting minimum GPU frequency index to $index_min ..."

if [ "$CK_GPU_FREQ_INDEX_MAX" != "" ]; then
  index_max=$CK_GPU_FREQ_INDEX_MAX
else
  index_max=$index
fi
echo "    Setting maximum GPU frequency index to $index_max ..."

echo

all_freqs=(`su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/available_frequencies`)
freq_min=${all_freqs[$index_min]}
freq_max=${all_freqs[$index_max]}

# This works for both stepping down and stepping up of the frequency index.
echo "    Setting maximum GPU frequency to $freq_max Hz ..."
echo $freq_max | su -c tee /sys/class/misc/mali0/device/devfreq/gpufreq/max_freq
echo "    Setting minimum GPU frequency to $freq_min Hz ..."
echo $freq_min | su -c tee /sys/class/misc/mali0/device/devfreq/gpufreq/min_freq
echo "    Setting maximum GPU frequency to $freq_max Hz ..."
echo $freq_max | su -c tee /sys/class/misc/mali0/device/devfreq/gpufreq/max_freq

echo

echo "    Printing minimum GPU frequency ..."
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/min_freq
echo "    Printing maximum GPU frequency ..."
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/max_freq
echo "    Printing current GPU frequency ..."
su -c cat /sys/class/misc/mali0/device/devfreq/gpufreq/cur_freq

