#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin (info provided by Anton Lokhmotov)
#

export CK_GPU_FREQ_GOVERNER=1

su -c . ck-set-gpu-online-and-frequency 260
