#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin
#

export PATH=/data/local/tmp/tools:$PATH

export CK_CPU_FREQ_GOVERNOR=performance

cpuinfo_max_freq=`cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq`

export CK_CPU_FREQ_FILE=cpuinfo_max_freq
export CK_CPU_ONLINE=1

su -c . ck-set-cpu-online-and-frequency $cpuinfo_max_freq
