#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin (info provided by Anton Lokhmotov)
#

# Governors:
# 0 - Default
# 1 - Interactive
# 2 - Static
# 3 - Booster

# FGG notices strange thing: if setting freq to max (650),
#   then CLBlast gives 13GFlops
#   but if seeting freq to 0, we get 18GFlops ...

export CK_GPU_FREQ_GOVERNER=3
su -c . ck-set-gpu-online-and-frequency 0
