#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin (info provided by Anton Lokhmotov)
#

governer=Interactive
if [ "$CK_GPU_FREQ_GOVERNER" != "" ]; then
 governer=$CK_GPU_FREQ_GOVERNER
fi

for cpudir in /sys/class/misc/mali*
do
   if [ -f "$cpudir/device/clock" ]; then
     echo "*** Processing $cpudir ..."

     echo "    Setting $governer governor ..."
     echo $governer | tee $cpudir/device/dvfs_governor

     echo "    Turn off adaptive governor ..."
     echo 0 | tee $cpudir/device/dvfs

     if [ "$1" != "" ]; then
        frequency=$1
     fi
     if [ "$CK_GPU_FREQ" != "" ]; then
        frequency=$CK_GPU_FREQ
     fi

     echo "    Setting min/max frequency=$frequency ..."
     echo $frequency | tee $cpudir/device/clock

     echo ""
     echo "    Checking current freq: $(cat $cpudir/device/clock)"
     echo "    Checking that adaptive governor is off (should be 0): $(cat $cpudir/device/dvfs)"
   fi
done
