#! /bin/bash

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin
#

echo "WARNING: this is a dummy script to set CPU and GPU frequency! Note that performance may vary! You should modify scripts for your platform!"
