#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin (info provided by Anton Lokhmotov)
#
echo off > /sys/devices/ffa30000.gpu/misc/mali0/device/dvfs
governor="powersave"
if [ "$CK_GPU_FREQ_GOVERNER" != "" ]; then
 governor=$CK_GPU_FREQ_GOVERNER
fi


if [ "$1" != "" ]; then
   frequency=$1
fi
if [ "$CK_GPU_FREQ" != "" ]; then
   frequency=$CK_GPU_FREQ
fi

echo "    Setting min/max frequency=$frequency ..."
echo $frequency >  /sys/devices/ffa30000.gpu/misc/mali0/device/clock



