#! /bin/bash

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin
#

governer=powersave
if [ "$CK_CPU_FREQ_GOVERNER" != "" ]; then
 governer=$CK_CPU_FREQ_GOVERNER
fi

freqfile=cpuinfo_max_freq
if [ "$CK_CPU_FREQ_FILE" != "" ]; then
 freqfile=$CK_CPU_FREQ_FILE
fi

online=1
if [ "$CK_CPU_ONLINE" != "" ]; then
 online=$CK_CPU_ONLINE
fi

if [ "$online" == "1" ] ; then
  echo "    Setting CPU cores ..."

  for cpudir in /sys/devices/system/cpu/cpu*
  do
    if [ -f "$cpudir/online" ] ; then
      # Check individual cores
      XONLINE=$online

      CPU_NUM=${cpudir:27:29}
      VAR_CPU_NUM=CK_CPU${CPU_NUM}_ONLINE
      if [ "${!VAR_CPU_NUM}" != "" ]; then
         XONLINE="${!VAR_CPU_NUM}"
      fi

      echo "      * CPU $CPU_NUM = ${XONLINE}"

      echo $XONLINE | sudo tee $cpudir/online >/dev/null
    fi
  done
fi

for cpudir in /sys/devices/system/cpu/cpu*
do
  CPU_NUM=${cpudir:27:29}
  VAR_CPU_NUM=CK_CPU${CPU_NUM}_ONLINE

  if [ -d "$cpudir/cpufreq" ] && 
     [ -f "$cpudir/cpufreq/scaling_governor" ] &&
     [ -f "$cpudir/online" ] && 
     [ "${!VAR_CPU_NUM}" != "0" ]; then

     echo "*** Processing $cpudir ..."

     echo "    Setting $governer state ..."
     echo $governer | sudo tee $cpudir/cpufreq/scaling_governor

     frequency=$(cat $cpudir/cpufreq/$freqfile)
     if [ "$1" != "" ]; then
        frequency=$1
     fi
     if [ "$CK_CPU_FREQ" != "" ]; then
        frequency=$CK_CPU_FREQ
     fi


     echo "    Setting min/max frequency=$frequency ..."
     echo $frequency | sudo tee $cpudir/cpufreq/scaling_max_freq
     echo $frequency | sudo tee $cpudir/cpufreq/scaling_min_freq
     echo $frequency | sudo tee $cpudir/cpufreq/scaling_max_freq

     echo "$(cat $cpudir/cpufreq/scaling_cur_freq)"

     if [ "$online" == "0" ]; then
        echo "    Bringing CPU offline ..."
        echo $online | sudo tee $cpudir/online
     fi
  fi
done
