#! /bin/bash

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin
#

cd "$(dirname "${BASH_SOURCE[0]}")"
. ck-set-cpu-powersave
. ck-set-gpu-powersave
