#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developers: Grigori Fursin, Anton Lokhmotov
#

curr_dir=$( cd "$(dirname "$0")" ; pwd -P )
$curr_dir/ck-set-cpu-powersave
$curr_dir/ck-set-gpu-powersave
