#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin (info provided by Anton Lokhmotov)
#

export CK_GPU_FREQ_GOVERNOR=performance
export CK_GPU_DVFS_ENABLE=0
myfreq=(`cat /proc/gpufreq/gpufreq_opp_dump | cut -d "," -f1 |  cut -d " " -f4`)
gpu_max_freq=${myfreq[0]}
echo $gpu_max_freq
./ck-set-gpu-online-and-frequency $gpu_max_freq
