#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developers: Grigori Fursin, Anton Lokhmotov
#

# DISABLE DVFS

dvfs=1
if [ "$CK_GPU_DVFS_ENABLE" == "0" ]; then
   echo Fixed freq mode
   dvfs=0   
fi

echo "    Setting DVFS=$dvfs ..."
echo $dvfs > /proc/gpufreq/gpufreq_opp_freq
if [ "$1" != "" ]; then
   frequency=$1
fi

if [ "$CK_GPU_FREQ" != "" ]; then
   frequency=$CK_GPU_FREQ
fi

echo "    Setting min/max frequency=$frequency ..."
echo $frequency > /proc/gpufreq/gpufreq_opp_freq

if [ "$CK_GPU_DVFS_ENABLE" == "1" ]; then
     echo $dvfs > /proc/gpufreq/gpufreq_opp_freq
fi
