#! /bin/bash

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developer: Grigori Fursin 
#

echo "Odroid state:"
echo ""
echo "  Exynos5 fans:"
sudo cat /sys/devices/*/pwm_duty
