#! /system/bin/sh

#
# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK Copyright.txt for copyright details.
#
# Developer: Grigori Fursin
#

export PATH=/data/local/tmp/tools:$PATH

export CK_CPU_FREQ_GOVERNER=performance
export CK_CPU_FREQ_FILE=cpuinfo_max_freq
export CK_CPU_ONLINE=1

. ck-set-cpu-online-and-frequency
