#! /bin/bash

# Collective Knowledge (CK)
#
# See CK LICENSE.txt for licensing details.
# See CK COPYRIGHT.txt for copyright details.
#
# Developers: Grigori Fursin, Flavio Vella, Anton Lokhmotov.

export governor=powersave

export CK_CPU_FREQ_GOVERNOR=$governor
export CK_CPU_FREQ_FILE=cpuinfo_min_freq
export CK_CPU_ONLINE=1

cd "$(dirname "${BASH_SOURCE[0]}")"
. ck-set-cpu-online-and-frequency
